# See https://pre-commit.com for more information
default_language_version:
  # default language version for each language used in the repository
  python: python3.8
repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
        args: [--application-directories=api, --exclude=migrations]

  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
        name: isort (python)
        exclude: "[a-zA-Z]*/(migrations)/(.)*"

  # update py
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.10.0
    hooks:
      - id: pyupgrade
        args: [ "--py36-plus", "--py37-plus", "--py38-plus"]

  # reformat code
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: "[a-zA-Z]*/(migrations)/(.)*"

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: [ "-iii", "-ll" ]

  # validate PEP8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
      additional_dependencies: [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
        ]
      exclude: "[a-zA-Z]*/(migrations)/(.)*"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.940
    hooks:
    - id: mypy
      name: mypy
      description: 'Date Type'
      args: [--no-strict-optional, --ignore-missing-imports, --scripts-are-modules]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    # See https://pre-commit.com/hooks.html for more hooks
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [ "--django" ]
      - id: trailing-whitespace
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
