version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shoes
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456789
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=shoes
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456789
    depends_on:
      - db
# volumes:
#   - ./data/db: